--DDL

--CRIAR BANCO DE DADOS

CREATE DATABASE Locadora

USE Locadora

--CRIAR TABELAS E COLUNAS 

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (50) NOT NULL,
	CPF VARCHAR (11) NOT NULL
)

CREATE TABLE Empresa 
(
	Idempresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (30) NOT NULL
)

CREATE TABLE Marca 
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (30)
)

CREATE TABLE MODELO 
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (30)
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa (IdEmpresa),
	IdModelo INT FOREIGN KEY REFERENCES MODELO (IdModelo),
	IdMarca INT FOREIGN KEY REFERENCES Marca (IdMarca),
	Placa VARCHAR (15) NOT NULL
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo (IdVeiculo),
	IdCliente INT FOREIGN KEY REFERENCES Cliente (IdCliente),
	Protocolo VARCHAR (60) NOT NULL
)