--DDL

CREATE DATABASE Clinica

USE Clinica 

-- CRIAR TABELAS 

CREATE TABLE Clinica 
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR (70) NOT NULL
)

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR (30) NOT NULL
)

CREATE TABLE TipoPet 
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR (30) NOT NULL
)

CREATE TABLE Raca 
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR (30) NOT NULL
)

CREATE TABLE Pet 
(
	IdPet INT PRIMARY KEY  IDENTITY,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet (IdTipoPet),
	IdRaca INT FOREIGN KEY REFERENCES Raca (IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Dono (IdDono),
	Nome VARCHAR (30) NOT NULL,
	DataDeNascimento VARCHAR (20) NOT NULL
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica (IdClinica),
	Nome VARCHAR (30) NOT NULL,
	CRMV VARCHAR (20) NOT NULL
)

CREATE TABLE Atendimentos 
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario (IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet (IdPet)
)

